export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function simulateError(count:number) {
  return Math.floor(Math.random()*count);
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const random = simulateError(2);
  if(random === 1) {
    throw new Error("Failed to load data");
  }
  return (
    <>
        {children}
        <p>Posts footer</p>
    </>
  )
}
