import { notFound } from "next/navigation"
import { Metadata } from "next"

type Props = {params: { postId: string}}

export const generateMetadata = async ({ params }: Props): Promise<Metadata> => {
  const title = await new Promise(resolve => {
    setTimeout(() => {
      resolve(`${params.postId}`)
    },1000)
  })
  return {
    title: `Post ${title}`,
    description: 'Generated by Next.js',
  }
}

export default function PostId({ params }: Props){
  if(parseInt(params.postId) > 10) return notFound()
  return (
    <h1>This is a individual page to a post {params.postId}</h1>
  )
}