export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// so here we can see that the RootLayout component is a simple wrapper for the children prop

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>Header</h1>
        {children}
        <h1>Footer</h1>
      </body>
    </html>
  )
}
