import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: "", // absolute title, use in other pages to override templates
    default: "Mastery Next.js", // default title
    template: "%s | Mastery Next.js", // dynamic titles
  },
  description: 'Generated by Next.js',
}

// so here we can see that the RootLayout component is a simple wrapper for the children prop

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>Header</h1>
        {children}
        <h1>Footer</h1>
      </body>
    </html>
  )
}
